
image: docker:19

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: 'tcp://localhost:2375'


services:
  - name: docker:19-dind
    command:
      - /bin/sh
      - -c
      - |
        echo "$CI_SERVER_TLS_CA_FILE" > /etc/ssl/certs/gitlab.jicd.lgsdirect.com.crt || exit
        dockerd-entrypoint.sh || exit
before_script:
  - REGISTRY_HOST=$CI_REGISTRY
  - REGISTRY_USER=$CI_REGISTRY_USER
  - REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD
build-job:
  stage: build
  script:
  - mkdir -p /etc/docker/certs.d/jicdimages.jicd.lgsdirect.com:5000
  - cp root-users-servers.crt /etc/docker/certs.d/jicdimages.jicd.lgsdirect.com:5000/ca.crt
  - docker login -u "ryan-robinson1" -p "$CI_REGISTRY_PASSWORD" jicdimages.jicd.lgsdirect.com:5000/certexpiry
  - docker ps
  - update-ca-certificates
  - docker build -t jicdimages.jicd.lgsdirect.com:5000/certexpiry .
  - docker push jicdimages.jicd.lgsdirect.com:5000/certexpiry

